version: '3.7'

services:
  message:
    build:
      context: .
      dockerfile: Dockerfile
    image: message
    container_name: message
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: message
      SERVICE_TAGS: dev
    networks:
      - app-network
    volumes:
      - ./message:/var/www/html
    ports:
      - "8080:80"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    tty: true
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    tty: true
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge