dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/dmitriysta/messenger/message/internal/interfaces:
    interfaces:
      MessageService:
      MessageRepository:
      RedisClient: