version: '3.7'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    image: user
    container_name: user
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: user
      SERVICE_TAGS: dev
    networks:
      - app-network
    volumes:
      - ./user:/var/www/html
    ports:
      - "8081:80"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    tty: true
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    tty: true
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge